var productList = {
    "bmw-1" : {
        "product-name" : "I4",
        "automaker" : "BMW",
        "price" : 3739000000,
        "year" : 2018,
        "photo-main" :  "../images/product/bmw/BMW-I4-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/bmw/BMW-I4-2.avif",
                        "../images/product/bmw/BMW-I4-3.avif",
                        "../images/product/bmw/BMW-I4-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I4-5.avif",
                        "../images/product/bmw/BMW-I4-6.avif",
                        "../images/product/bmw/BMW-I4-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I4-8.avif",
                        "../images/product/bmw/BMW-I4-9.avif",
                        "../images/product/bmw/BMW-I4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-I4-11.avif",
                        "../images/product/bmw/BMW-I4-12.avif",
                        "../images/product/bmw/BMW-I4-13.avif", 
        ],
    },
    "bmw-2" : {
        "product-name" : "I5",
        "automaker" : "BMW",
        "price" : 2599000000,
        "year" : 2020,
        "photo-main" :  "../images/product/bmw/BMW-I5-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-I5-2.avif",
                        "../images/product/bmw/BMW-I5-3.avif",
                        "../images/product/bmw/BMW-I4-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I5-5.avif",
                        "../images/product/bmw/BMW-I5-6.avif",
                        "../images/product/bmw/BMW-I5-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I4-8.avif",
                        "../images/product/bmw/BMW-I4-9.avif",
                        "../images/product/bmw/BMW-I4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-I4-11.avif",
                        "../images/product/bmw/BMW-I4-12.avif",
                        "../images/product/bmw/BMW-I4-13.avif", 
        ],
    },
    "bmw-3" : {
        "product-name" : "I7",
        "automaker" : "BMW",
        "price" : 6499000000,
        "year" : 2022,
        "photo-main" :  "../images/product/bmw/BMW-I7-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-I7-2.avif",
                        "../images/product/bmw/BMW-I7-3.avif",
                        "../images/product/bmw/BMW-I7-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I7-5.avif",
                        "../images/product/bmw/BMW-I7-6.avif",
                        "../images/product/bmw/BMW-I7-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I4-8.avif",
                        "../images/product/bmw/BMW-I4-9.avif",
                        "../images/product/bmw/BMW-I4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-I4-11.avif",
                        "../images/product/bmw/BMW-I4-12.avif",
                        "../images/product/bmw/BMW-I4-13.avif", 
        ],
    },
    "bmw-4" : {
        "product-name" : "IX",
        "automaker" : "BMW",
        "price" : 3229000000,
        "year" : 2020,
        "photo-main" :  "../images/product/bmw/BMW-IX-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-IX-2.avif",
                        "../images/product/bmw/BMW-IX-3.avif",
                        "../images/product/bmw/BMW-IX-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-IX-5.avif",
                        "../images/product/bmw/BMW-IX-6.avif",
                        "../images/product/bmw/BMW-IX-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-I4-8.avif",
                        "../images/product/bmw/BMW-I4-9.avif",
                        "../images/product/bmw/BMW-I4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-I4-11.avif",
                        "../images/product/bmw/BMW-I4-12.avif",
                        "../images/product/bmw/BMW-I4-13.avif", 
        ],
    },
    "bmw-5" : {
        "product-name" : "M2",
        "automaker" : "BMW",
        "price" : 2999000000,
        "year" : 2010,
        "photo-main" :  "../images/product/bmw/BMW-M2-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-M2-2.avif",
                        "../images/product/bmw/BMW-M2-3.avif",
                        "../images/product/bmw/BMW-M2-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-M2-5.avif",
                        "../images/product/bmw/BMW-M2-6.avif",
                        "../images/product/bmw/BMW-M2-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-M4-8.avif",
                        "../images/product/bmw/BMW-M4-9.avif",
                        "../images/product/bmw/BMW-M4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-M4-11.avif",
                        "../images/product/bmw/BMW-M4-12.avif",
                        "../images/product/bmw/BMW-M4-13.avif", 
        ],
    },
    "bmw-6" : {
        "product-name" : "M4",
        "automaker" : "BMW",
        "price" : 4239000000,
        "year" : 2013,
        "photo-main" :  "../images/product/bmw/BMW-M4-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-M4-2.avif",
                        "../images/product/bmw/BMW-M4-3.avif",
                        "../images/product/bmw/BMW-M4-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-M4-5.avif",
                        "../images/product/bmw/BMW-M4-6.avif",
                        "../images/product/bmw/BMW-M4-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-M4-8.avif",
                        "../images/product/bmw/BMW-M4-9.avif",
                        "../images/product/bmw/BMW-M4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-M4-11.avif",
                        "../images/product/bmw/BMW-M4-12.avif",
                        "../images/product/bmw/BMW-M4-13.avif", 
        ],
    },
    "bmw-7" : {
        "product-name" : "M8",
        "automaker" : "BMW",
        "price" : 12939000000,
        "year" : 2024,
        "photo-main" :  "../images/product/bmw/BMW-M8-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-M8-2.avif",
                        "../images/product/bmw/BMW-M8-3.avif",
                        "../images/product/bmw/BMW-M8-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-M8-5.avif",
                        "../images/product/bmw/BMW-M8-6.avif",
                        "../images/product/bmw/BMW-M8-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-M4-8.avif",
                        "../images/product/bmw/BMW-M4-9.avif",
                        "../images/product/bmw/BMW-M4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-M4-11.avif",
                        "../images/product/bmw/BMW-M4-12.avif",
                        "../images/product/bmw/BMW-M4-13.avif", 
        ],
    },
    "bmw-8" : {
        "product-name" : "XM",
        "automaker" : "BMW",
        "price" : 10999000000,
        "year" : 2023,
        "photo-main" :  "../images/product/bmw/BMW-XM-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-XM-2.avif",
                        "../images/product/bmw/BMW-XM-3.avif",
                        "../images/product/bmw/BMW-XM-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-XM-5.avif",
                        "../images/product/bmw/BMW-XM-6.avif",
                        "../images/product/bmw/BMW-XM-7.avif",
        ],
        "interior" : [    
            "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
            "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
            "../images/product/bmw/BMW-X3-8.avif",
            "../images/product/bmw/BMW-X3-9.avif",
            "../images/product/bmw/BMW-X3-10.avif",
],
"accessory" : [
            "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
            "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
            "../images/product/bmw/BMW-X3-11.avif",
            "../images/product/bmw/BMW-X3-12.avif",
            "../images/product/bmw/BMW-X3-13.avif", 
],
    },
    "bmw-9" : {
        "product-name" : "X3",
        "automaker" : "BMW",
        "price" : 1795000000,
        "year" : 2012,
        "photo-main" :  "../images/product/bmw/BMW-X3-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-X3-2.avif",
                        "../images/product/bmw/BMW-X3-3.avif",
                        "../images/product/bmw/BMW-X3-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X3-5.avif",
                        "../images/product/bmw/BMW-X3-6.avif",
                        "../images/product/bmw/BMW-X3-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X3-8.avif",
                        "../images/product/bmw/BMW-X3-9.avif",
                        "../images/product/bmw/BMW-X3-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-X3-11.avif",
                        "../images/product/bmw/BMW-X3-12.avif",
                        "../images/product/bmw/BMW-X3-13.avif", 
        ],
    },
    "bmw-10" : {
        "product-name" : "X4",
        "automaker" : "BMW",
        "price" : 2899000000,
        "year" : 2014,
        "photo-main" :  "../images/product/bmw/BMW-X4-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-X4-2.avif",
                        "../images/product/bmw/BMW-X4-3.avif",
                        "../images/product/bmw/BMW-X4-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X4-5.avif",
                        "../images/product/bmw/BMW-X4-6.avif",
                        "../images/product/bmw/BMW-X4-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X3-8.avif",
                        "../images/product/bmw/BMW-X3-9.avif",
                        "../images/product/bmw/BMW-X3-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-X3-11.avif",
                        "../images/product/bmw/BMW-X3-12.avif",
                        "../images/product/bmw/BMW-X3-13.avif", 
        ],
    },
    "bmw-11" : {
        "product-name" : "X5",
        "automaker" : "BMW",
        "price" : 3909000000,
        "year" : 2017,
        "photo-main" :  "../images/product/bmw/BMW-X5-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-X5-2.avif",
                        "../images/product/bmw/BMW-X5-3.avif",
                        "../images/product/bmw/BMW-X5-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X5-5.avif",
                        "../images/product/bmw/BMW-X5-6.avif",
                        "../images/product/bmw/BMW-X5-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X3-8.avif",
                        "../images/product/bmw/BMW-X3-9.avif",
                        "../images/product/bmw/BMW-X3-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-X3-11.avif",
                        "../images/product/bmw/BMW-X3-12.avif",
                        "../images/product/bmw/BMW-X3-13.avif", 
        ],
    },
    "bmw-12" : {
        "product-name" : "X6",
        "automaker" : "BMW",
        "price" : 3799000000,
        "year" : 2021,
        "photo-main" :  "../images/product/bmw/BMW-X6-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-X6-2.avif",
                        "../images/product/bmw/BMW-X6-3.avif",
                        "../images/product/bmw/BMW-X6-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X6-5.avif",
                        "../images/product/bmw/BMW-X6-6.avif",
                        "../images/product/bmw/BMW-X6-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X3-8.avif",
                        "../images/product/bmw/BMW-X3-9.avif",
                        "../images/product/bmw/BMW-X3-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-X3-11.avif",
                        "../images/product/bmw/BMW-X3-12.avif",
                        "../images/product/bmw/BMW-X3-13.avif", 
        ],
    },
    "bmw-13" : {
        "product-name" : "X7",
        "automaker" : "BMW",
        "price" : 5149000000,
        "year" : 2023,
        "photo-main" :  "../images/product/bmw/BMW-X7-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/bmw/BMW-X7-2.avif",
                        "../images/product/bmw/BMW-X7-3.avif",
                        "../images/product/bmw/BMW-X7-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X7-5.avif",
                        "../images/product/bmw/BMW-X7-6.avif",
                        "../images/product/bmw/BMW-X7-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/bmw/BMW-X3-8.avif",
                        "../images/product/bmw/BMW-X3-9.avif",
                        "../images/product/bmw/BMW-X3-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/bmw/BMW-X3-11.avif",
                        "../images/product/bmw/BMW-X3-12.avif",
                        "../images/product/bmw/BMW-X3-13.avif", 
        ],
    },
    "mer-1" : {
        "product-name" : "GLC",
        "automaker" : "Mercedes",
        "price" : 2299000000,
        "year" : 2018,
        "photo-main" :  "../images/product/Mercedes/Mer-GLC-3.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-GLC-2.avif",
                        "../images/product/Mercedes/Mer-GLC-1.avif",
                        "../images/product/Mercedes/Mer-GLC-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GT63-5.avif",
                        "../images/product/Mercedes/Mer-GT63-6.avif",
                        "../images/product/Mercedes/Mer-GT63-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLS-8.avif",
                        "../images/product/Mercedes/Mer-GLS-9.avif",
                        "../images/product/Mercedes/Mer-GLS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GLS-11.avif",
                        "../images/product/Mercedes/Mer-GLS-12.avif",
                        "../images/product/Mercedes/Mer-GLS-13.avif", 
        ],
    },
    "mer-2" : {
        "product-name" : "GLE",
        "automaker" : "Mercedes",
        "price" : 4359000000,
        "year" : 2020,
        "photo-main" :  "../images/product/Mercedes/Mer-GLE-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-GLE-2.avif",
                        "../images/product/Mercedes/Mer-GLE-3.avif",
                        "../images/product/Mercedes/Mer-GLE-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLE-5.avif",
                        "../images/product/Mercedes/Mer-GLE-6.avif",
                        "../images/product/Mercedes/Mer-GLE-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLS-8.avif",
                        "../images/product/Mercedes/Mer-GLS-9.avif",
                        "../images/product/Mercedes/Mer-GLS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GLS-11.avif",
                        "../images/product/Mercedes/Mer-GLS-12.avif",
                        "../images/product/Mercedes/Mer-GLS-13.avif", 
        ],
    },
    "mer-3" : {
        "product-name" : "GLI",
        "automaker" : "Mercedes",
        "price" : 5239000000,
        "year" : 2022,
        "photo-main" :  "../images/product/Mercedes/Mer-GLI-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-GLI-2.avif",
                        "../images/product/Mercedes/Mer-GLI-3.avif",
                        "../images/product/Mercedes/Mer-GLI-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLI-5.avif",
                        "../images/product/Mercedes/Mer-GLI-6.avif",
                        "../images/product/Mercedes/Mer-GLI-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLS-8.avif",
                        "../images/product/Mercedes/Mer-GLS-9.avif",
                        "../images/product/Mercedes/Mer-GLS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GLS-11.avif",
                        "../images/product/Mercedes/Mer-GLS-12.avif",
                        "../images/product/Mercedes/Mer-GLS-13.avif", 
        ],
    },
    "mer-4" : {
        "product-name" : "GLS",
        "automaker" : "Mercedes",
        "price" : 5799000000,
        "year" : 2024,
        "photo-main" :  "../images/product/Mercedes/Mer-GLS-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-GLS-2.avif",
                        "../images/product/Mercedes/Mer-GLS-3.avif",
                        "../images/product/Mercedes/Mer-GLS-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLS-5.avif",
                        "../images/product/Mercedes/Mer-GLS-6.avif",
                        "../images/product/Mercedes/Mer-GLS-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GLS-8.avif",
                        "../images/product/Mercedes/Mer-GLS-9.avif",
                        "../images/product/Mercedes/Mer-GLS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GLS-11.avif",
                        "../images/product/Mercedes/Mer-GLS-12.avif",
                        "../images/product/Mercedes/Mer-GLS-13.avif", 
        ],
    },
    "mer-5" : {
        "product-name" : "Class C",
        "automaker" : "Mercedes",
        "price" : 2199000000,
        "year" : 2019,
        "photo-main" :  "../images/product/Mercedes/Mer-CClass-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-CClass-2.avif",
                        "../images/product/Mercedes/Mer-CClass-3.avif",
                        "../images/product/Mercedes/Mer-CClass-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-CClass-5.avif",
                        "../images/product/Mercedes/Mer-CClass-6.avif",
                        "../images/product/Mercedes/Mer-CClass-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GT63-8.avif",
                        "../images/product/Mercedes/Mer-GT63-9.avif",
                        "../images/product/Mercedes/Mer-GT63-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GT63-11.avif",
                        "../images/product/Mercedes/Mer-GT63-12.avif",
                        "../images/product/Mercedes/Mer-GT63-13.avif", 
        ],
    },
    "mer-6" : {
        "product-name" : "Class E",
        "automaker" : "Mercedes",
        "price" : 1899000000,
        "year" : 2021,
        "photo-main" :  "../images/product/Mercedes/Mer-EClass-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-EClass-2.avif",
                        "../images/product/Mercedes/Mer-EClass-3.avif",
                        "../images/product/Mercedes/Mer-EClass-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-EClass-5.avif",
                        "../images/product/Mercedes/Mer-EClass-6.avif",
                        "../images/product/Mercedes/Mer-EClass-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GT63-8.avif",
                        "../images/product/Mercedes/Mer-GT63-9.avif",
                        "../images/product/Mercedes/Mer-GT63-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GT63-11.avif",
                        "../images/product/Mercedes/Mer-GT63-12.avif",
                        "../images/product/Mercedes/Mer-GT63-13.avif", 
        ],
    },
    "mer-7" : {
        "product-name" : "Class S",
        "automaker" : "Mercedes",
        "price" : 5079000000,
        "year" : 2023,
        "photo-main" :  "../images/product/Mercedes/Mer-SClass-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-SClass-2.avif",
                        "../images/product/Mercedes/Mer-SClass-3.avif",
                        "../images/product/Mercedes/Mer-SClass-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-SClass-5.avif",
                        "../images/product/Mercedes/Mer-SClass-6.avif",
                        "../images/product/Mercedes/Mer-SClass-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GT63-8.avif",
                        "../images/product/Mercedes/Mer-GT63-9.avif",
                        "../images/product/Mercedes/Mer-GT63-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GT63-11.avif",
                        "../images/product/Mercedes/Mer-GT63-12.avif",
                        "../images/product/Mercedes/Mer-GT63-13.avif", 
        ],
    },
    "mer-8" : {
        "product-name" : "Class GT63",
        "automaker" : "Mercedes",
        "price" : 12499000000,
        "year" : 2024,
        "photo-main" :  "../images/product/Mercedes/Mer-GT63-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-GT63-2.avif",
                        "../images/product/Mercedes/Mer-GT63-3.avif",
                        "../images/product/Mercedes/Mer-GT63-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GT63-5.avif",
                        "../images/product/Mercedes/Mer-GT63-6.avif",
                        "../images/product/Mercedes/Mer-GT63-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-GT63-8.avif",
                        "../images/product/Mercedes/Mer-GT63-9.avif",
                        "../images/product/Mercedes/Mer-GT63-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-GT63-11.avif",
                        "../images/product/Mercedes/Mer-GT63-12.avif",
                        "../images/product/Mercedes/Mer-GT63-13.avif", 
        ],
    },
    "mer-9" : {
        "product-name" : "450",
        "automaker" : "Mercedes",
        "price" : 5249000000,
        "year" : 2017,
        "photo-main" :  "../images/product/Mercedes/Mer-450-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-450-2.avif",
                        "../images/product/Mercedes/Mer-450-3.avif",
                        "../images/product/Mercedes/Mer-450-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-450-5.avif",
                        "../images/product/Mercedes/Mer-450-6.avif",
                        "../images/product/Mercedes/Mer-450-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-EQS-8.avif",
                        "../images/product/Mercedes/Mer-EQS-9.avif",
                        "../images/product/Mercedes/Mer-EQS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-EQS-11.avif",
                        "../images/product/Mercedes/Mer-EQS-12.avif",
                        "../images/product/Mercedes/Mer-EQS-13.avif", 
        ],
    },
    "mer-10" : {
        "product-name" : "580",
        "automaker" : "Mercedes",
        "price" : 5966000000,
        "year" : 2020,
        "photo-main" :  "../images/product/Mercedes/Mer-580-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-580-2.avif",
                        "../images/product/Mercedes/Mer-580-3.avif",
                        "../images/product/Mercedes/Mer-580-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-580-5.avif",
                        "../images/product/Mercedes/Mer-580-6.avif",
                        "../images/product/Mercedes/Mer-580-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-EQS-8.avif",
                        "../images/product/Mercedes/Mer-EQS-9.avif",
                        "../images/product/Mercedes/Mer-EQS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-EQS-11.avif",
                        "../images/product/Mercedes/Mer-EQS-12.avif",
                        "../images/product/Mercedes/Mer-EQS-13.avif", 
        ],
    },
    "mer-11" : {
        "product-name" : "AMG",
        "automaker" : "Mercedes",
        "price" : 2329000000,
        "year" : 2021,
        "photo-main" :  "../images/product/Mercedes/Mer-AMG-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-AMG-2.avif",
                        "../images/product/Mercedes/Mer-AMG-3.avif",
                        "../images/product/Mercedes/Mer-AMG-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-AMG-5.avif",
                        "../images/product/Mercedes/Mer-AMG-6.avif",
                        "../images/product/Mercedes/Mer-AMG-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-EQS-8.avif",
                        "../images/product/Mercedes/Mer-EQS-9.avif",
                        "../images/product/Mercedes/Mer-EQS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-EQS-11.avif",
                        "../images/product/Mercedes/Mer-EQS-12.avif",
                        "../images/product/Mercedes/Mer-EQS-13.avif", 
        ],
    },
    "mer-12" : {
        "product-name" : "EQS",
        "automaker" : "Mercedes",
        "price" : 4839000000,
        "year" : 2024,
        "photo-main" :  "../images/product/Mercedes/Mer-EQS-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/Mercedes/Mer-EQS-2.avif",
                        "../images/product/Mercedes/Mer-EQS-3.avif",
                        "../images/product/Mercedes/Mer-EQS-4.avif",
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-EQS-5.avif",
                        "../images/product/Mercedes/Mer-EQS-6.avif",
                        "../images/product/Mercedes/Mer-EQS-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/Mercedes/Mer-EQS-8.avif",
                        "../images/product/Mercedes/Mer-EQS-9.avif",
                        "../images/product/Mercedes/Mer-EQS-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/Mercedes/Mer-EQS-11.avif",
                        "../images/product/Mercedes/Mer-EQS-12.avif",
                        "../images/product/Mercedes/Mer-EQS-13.avif", 
        ],
    },
    "toy-1" : {
        "product-name" : "Mirai",
        "automaker" : "Toyota",
        "price" : 1250000000,
        "year" : 2024,
        "photo-main" :  "../images/product/toyota/Toyota-Mirai-1.avif",
        "technical-specification" : [    
                        "1-speed","136kW","Dien","1.24kW/h","2024",
                        "1.8m-4.9m-1.5m","1920kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Mirai-2.avif",
                        "../images/product/toyota/Toyota-Mirai-3.avif",
                        "../images/product/toyota/Toyota-Mirai-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Mirai-5.avif",
                        "../images/product/toyota/Toyota-Mirai-6.avif",
                        "../images/product/toyota/Toyota-Mirai-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Mirai-8.avif",
                        "../images/product/toyota/Toyota-Mirai-9.avif",
                        "../images/product/toyota/Toyota-Mirai-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Mirai-11.avif",
                        "../images/product/toyota/Toyota-Mirai-12.avif",
                        "../images/product/toyota/Toyota-Mirai-13.avif", 
        ],
    },
    "toy-2" : {
        "product-name" : "Corolla",
        "automaker" : "Toyota",
        "price" : 955000000,
        "year" : 2023,
        "photo-main" :  "../images/product/toyota/Toyota-Corolla-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2023",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Corolla-2.avif",
                        "../images/product/toyota/Toyota-Corolla-3.avif",
                        "../images/product/toyota/Toyota-Corolla-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Corolla-5.avif",
                        "../images/product/toyota/Toyota-Corolla-6.avif",
                        "../images/product/toyota/Toyota-Corolla-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Corolla-8.avif",
                        "../images/product/toyota/Toyota-Corolla-9.avif",
                        "../images/product/toyota/Toyota-Corolla-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Corolla-11.avif",
                        "../images/product/toyota/Toyota-Corolla-12.avif",
                        "../images/product/toyota/Toyota-Corolla-13.avif", 
        ],
    },
    "toy-3" : {
        "product-name" : "Prius",
        "automaker" : "Toyota",
        "price" : 626000000,
        "year" : 2020,
        "photo-main" :  "../images/product/toyota/Toyota-Prius-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2020",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Prius-2.avif",
                        "../images/product/toyota/Toyota-Prius-3.avif",
                        "../images/product/toyota/Toyota-Prius-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Prius-5.avif",
                        "../images/product/toyota/Toyota-Prius-6.avif",
                        "../images/product/toyota/Toyota-Prius-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Prius-8.avif",
                        "../images/product/toyota/Toyota-Prius-9.avif",
                        "../images/product/toyota/Toyota-Prius-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Prius-11.avif",
                        "../images/product/toyota/Toyota-Prius-12.avif",
                        "../images/product/toyota/Toyota-Prius-13.avif", 
        ],
    },
    "toy-4" : {
        "product-name" : "Camry",
        "automaker" : "Toyota",
        "price" : 1105000000,
        "year" : 2023,
        "photo-main" :  "../images/product/toyota/Toyota-Camry-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2023",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Camry-2.avif",
                        "../images/product/toyota/Toyota-Camry-3.avif",
                        "../images/product/toyota/Toyota-Camry-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Camry-5.avif",
                        "../images/product/toyota/Toyota-Camry-6.avif",
                        "../images/product/toyota/Toyota-Camry-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Camry-8.avif",
                        "../images/product/toyota/Toyota-Camry-9.avif",
                        "../images/product/toyota/Toyota-Camry-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Camry-11.avif",
                        "../images/product/toyota/Toyota-Camry-12.avif",
                        "../images/product/toyota/Toyota-Camry-13.avif", 
        ],
    },
    "toy-5" : {
        "product-name" : "Crown",
        "automaker" : "Toyota",
        "price" : 976000000,
        "year" : 2020,
        "photo-main" :  "../images/product/toyota/Toyota-Crown-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2020",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Crown-2.avif",
                        "../images/product/toyota/Toyota-Crown-3.avif",
                        "../images/product/toyota/Toyota-Crown-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Crown-5.avif",
                        "../images/product/toyota/Toyota-Crown-6.avif",
                        "../images/product/toyota/Toyota-Crown-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Crown-8.avif",
                        "../images/product/toyota/Toyota-Crown-9.avif",
                        "../images/product/toyota/Toyota-Crown-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Crown-11.avif",
                        "../images/product/toyota/Toyota-Crown-12.avif",
                        "../images/product/toyota/Toyota-Crown-13.avif", 
        ],
    },
    "toy-6" : {
        "product-name" : "Sequoia",
        "automaker" : "Toyota",
        "price" : 7250000000,
        "year" : 2014,
        "photo-main" :  "../images/product/toyota/Toyota-Sequoia-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2014",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Sequoia-2.avif",
                        "../images/product/toyota/Toyota-Sequoia-3.avif",
                        "../images/product/toyota/Toyota-Sequoia-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Sequoia-5.avif",
                        "../images/product/toyota/Toyota-Sequoia-6.avif",
                        "../images/product/toyota/Toyota-Sequoia-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Sequoia-8.avif",
                        "../images/product/toyota/Toyota-Sequoia-9.avif",
                        "../images/product/toyota/Toyota-Sequoia-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Sequoia-11.avif",
                        "../images/product/toyota/Toyota-Sequoia-12.avif",
                        "../images/product/toyota/Toyota-Sequoia-13.avif", 
        ],
    },
    "toy-7" : {
        "product-name" : "RAV4",
        "automaker" : "Toyota",
        "price" : 2600000000,
        "year" : 2020,
        "photo-main" :  "../images/product/toyota/Toyota-RAV4-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2020",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-RAV4-2.avif",
                        "../images/product/toyota/Toyota-RAV4-3.avif",
                        "../images/product/toyota/Toyota-RAV4-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-RAV4-5.avif",
                        "../images/product/toyota/Toyota-RAV4-6.avif",
                        "../images/product/toyota/Toyota-RAV4-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-RAV4-8.avif",
                        "../images/product/toyota/Toyota-RAV4-9.avif",
                        "../images/product/toyota/Toyota-RAV4-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-RAV4-11.avif",
                        "../images/product/toyota/Toyota-RAV4-12.avif",
                        "../images/product/toyota/Toyota-RAV4-13.avif", 
        ],
    },
    "toy-8" : {
        "product-name" : "Grand Highlander",
        "automaker" : "Toyota",
        "price" : 4900000000,
        "year" : 2023,
        "photo-main" :  "../images/product/toyota/Toyota-GrandHighlander-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2023",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-GrandHighlander-2.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-3.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-GrandHighlander-5.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-6.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-GrandHighlander-8.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-9.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-GrandHighlander-11.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-12.avif",
                        "../images/product/toyota/Toyota-GrandHighlander-13.avif", 
        ],
    },
    "toy-9" : {
        "product-name" : "4Runner",
        "automaker" : "Toyota",
        "price" : 4100000000,
        "year" : 2020,
        "photo-main" :  "../images/product/toyota/Toyota-4Runner-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2020",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-4Runner-2.avif",
                        "../images/product/toyota/Toyota-4Runner-3.avif",
                        "../images/product/toyota/Toyota-4Runner-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-4Runner-5.avif",
                        "../images/product/toyota/Toyota-4Runner-6.avif",
                        "../images/product/toyota/Toyota-4Runner-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-4Runner-8.avif",
                        "../images/product/toyota/Toyota-4Runner-9.avif",
                        "../images/product/toyota/Toyota-4Runner-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-4Runner-11.avif",
                        "../images/product/toyota/Toyota-4Runner-12.avif",
                        "../images/product/toyota/Toyota-4Runner-13.avif", 
],
    },
    "toy-10" : {
        "product-name" : "Tacoma",
        "automaker" : "Toyota",
        "price" : 5520000000,
        "year" : 2018,
        "photo-main" :  "../images/product/toyota/Toyota-Tacoma-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2018",
                        "2m-5m-1m","3000kg","1000kg","5 cho","EU",
                        "../images/product/toyota/Toyota-Tacoma-2.avif",
                        "../images/product/toyota/Toyota-Tacoma-3.avif",
                        "../images/product/toyota/Toyota-Tacoma-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Tacoma-5.avif",
                        "../images/product/toyota/Toyota-Tacoma-6.avif",
                        "../images/product/toyota/Toyota-Tacoma-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Tacoma-8.avif",
                        "../images/product/toyota/Toyota-Tacoma-9.avif",
                        "../images/product/toyota/Toyota-Tacoma-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Tacoma-11.avif",
                        "../images/product/toyota/Toyota-Tacoma-12.avif",
                        "../images/product/toyota/Toyota-Tacoma-13.avif", 
        ],
    },
    "toy-11" : {
        "product-name" : "Tundra",
        "automaker" : "Toyota",
        "price" : 2599000000,
        "year" : 2020,
        "photo-main" :  "../images/product/toyota/Toyota-Tundra-1.avif",
        "technical-specification" : [    
                        "tx1","300w","Xang","5l/100km","2024",
                        "2m-5m-1m","3000kg","1000kg","5 cho","VN",
                        "../images/product/toyota/Toyota-Tundra-2.avif",
                        "../images/product/toyota/Toyota-Tundra-3.avif",
                        "../images/product/toyota/Toyota-Tundra-4.avif",  
        ],
        "exterior" : [
                        "Digital light","<i class='fa-solid fa-x'></i>","Digital light","LED","LED",
                        "<i class='fa-solid fa-check'></i>","LED","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Tundra-5.avif",
                        "../images/product/toyota/Toyota-Tundra-6.avif",
                        "../images/product/toyota/Toyota-Tundra-7.avif",
        ],
        "interior" : [    
                        "Da","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","12,3 inch","<i class='fa-solid fa-check'></i>",
                        "4 vùng","<i class='fa-solid fa-check'></i>","OLED 12,3 inch","Burmester 15 loa","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "../images/product/toyota/Toyota-Tundra-8.avif",
                        "../images/product/toyota/Toyota-Tundra-9.avif",
                        "../images/product/toyota/Toyota-Tundra-10.avif",
        ],
        "accessory" : [
                        "Điện","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>",
                        "<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","<i class='fa-solid fa-check'></i>","8",
                        "../images/product/toyota/Toyota-Tundra-11.avif",
                        "../images/product/toyota/Toyota-Tundra-12.avif",
                        "../images/product/toyota/Toyota-Tundra-13.avif", 
        ],
    }
}
function displayToday() {
    var today = new Date();
    var day = today.getDate();
    var month = today.getMonth() + 1;
    var year = today.getFullYear();
    var formattedDate = day + '/' + month + '/' + year;
    document.getElementById("today").innerText = formattedDate;
}
function addDetail(Code){
    window.localStorage.setItem("detail", Code);
}
function show(typeCar){
    for (var i = 0 ; i < Object.keys(productList).length; i++){
        document.getElementById("product-name-"+(i+1).toString()).innerText = productList[typeCar+(i+1).toString()]["product-name"];
        document.getElementById("price-"+(i+1).toString()).innerText = "Giá từ "+productList[typeCar+(i+1).toString()]["price"].toLocaleString('vi-VN')+"đ";
        document.getElementById("year-"+(i+1).toString()).innerText = productList[typeCar+(i+1).toString()]["year"];
    }
}
function showPhoto(id,list,item){
    var container = document.getElementById(id);
    container.innerHTML="";
    for (var i = item[list].length-3; i < item[list].length ; i++){
        var photoCell = document.createElement("div");
        if ( i != item[list].length-1 )
            photoCell.innerHTML=" <div class='owl-item' style='width: 30%; margin-right: 5%;'><div class='ct' ><img src='"+ item[list][i] +"' alt=''></div>";
        else
            photoCell.innerHTML=" <div class='owl-item cloned' style='width: 30%;'><div class='ct'><img src='"+ item[list][i] +"' alt=''></div>";
        container.appendChild(photoCell);
    }
}
function showDetail(){
    var item = productList[window.localStorage.getItem('detail')];
    for (var i = 0 ; i < 10; i++){
        document.getElementById("technical-specification-"+(i+1).toString()).innerText = item["technical-specification"][i];
        if ( i == 1 || i == 5 || i == 7 || i == 8 || i == 9)
            document.getElementById("exterior-"+(i+1).toString()).innerHTML = item["exterior"][i];
        else
            document.getElementById("exterior-"+(i+1).toString()).innerText = item["exterior"][i];
        if ( i == 0 || i == 4 || i == 6 || i == 8 || i == 9)
            document.getElementById("interior-"+(i+1).toString()).innerText = item["interior"][i];
        else
            document.getElementById("interior-"+(i+1).toString()).innerHTML = item["interior"][i];
        if ( i == 0 || i == 9)
            document.getElementById("accessory-"+(i+1).toString()).innerText = item["accessory"][i];
        else
            document.getElementById("accessory-"+(i+1).toString()).innerHTML = item["accessory"][i];
    }
    document.getElementById("interior-11").innerHTML = item["interior"][10];
    document.getElementById("interior-12").innerHTML = item["interior"][11];
    showPhoto("photo-car-1","technical-specification",item);
    showPhoto("photo-car-2","exterior",item);
    showPhoto("photo-car-3","interior",item);
    showPhoto("photo-car-4","accessory",item);
    document.getElementById("photo-main").innerHTML="<img class='car-big-img' src='"+item["photo-main"]+"' alt='' style='height: 500px;'>";
    document.getElementById("product-name").innerText = item["product-name"];
    document.getElementById("automaker").innerText = item["automaker"];
    document.getElementById("year-of-manufacture").innerText = item["year"];
    document.getElementById("price").innerText = item["price"].toLocaleString('vi-VN')+"đ";
    displayToday(); 
    document.getElementById("title").innerText = item["product-name"];
}
